//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.27 at 04:58:50 PM CDT 
//


package com.safee.AirlineReservation.response;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.safee.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.safee.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetFlightRequest }
     * 
     */
    public GetFlightRequest createGetEmployeeRequest() {
        return new GetFlightRequest();
    }

    /**
     * Create an instance of {@link GetFlightResponse }
     * 
     */
    public GetFlightResponse createGetEmployeeResponse() {
        return new GetFlightResponse();
    }

    /**
     * Create an instance of {@link Flight }
     * 
     */
    public Flight createEmployee() {
        return new Flight();
    }

}
